### ISSUE TITLE
Package File in commands/misc/vote.js (Develop Branch)

### ISSUE THREAD

**Issue by Cszura** [Nookbot/Nookbot#42]
Hi there!
I beleive the first line in [commands/misc/vote.js](https://github.com/Nookbot/Nookbot/blob/develop/commands/misc/vote.js)
`const emojiRegex = require('emoji-regex/RGI_Emoji');`
i believe its supposed to be
`const emojiRegex = require('emoji-regex/RGI_Emoji.js');`

[NPMJS.com Website](https://www.npmjs.com/package/emoji-regex)
![image](https://user-images.githubusercontent.com/81977221/123465697-73e6b700-d5bc-11eb-81e4-c63bf56d9a44.png)

Hope this helps
:)

**Comment by Phoenix1128** [comment]
Since the function is exported from the file using `module.exports` it is not necessary to add `.js` to the end of the `require` line. We can use it as an exported module rather than an individual file. [emoji-regex/src/RGI_Emoji.js](https://github.com/mathiasbynens/emoji-regex/blob/main/src/RGI_Emoji.js) for reference.

![image](https://user-images.githubusercontent.com/44852385/123486497-224d2500-d5da-11eb-8e34-a9e70db35b7a.png)
